from .registration_serializer import RegistrationSerializer
from .login_serializer import LoginSerializer
from .user_serializer import UserSerializer, PublicUserSerializer, InstructorSerializer, SoldierSerializer
from .settings_serializer import SettingsSerializer
from .training_serializer import TrainingSerializer, TrainingDetailSerializer
from .task_serializer import TaskSerializer
from .admin_serializer import AdminCreationSerializer
from .mine_serializer import MineSerializer, MineUpdateSerializer
from .map_serializer import MapSerializer
from .results_serializer import ResultsSerializer